spring:
    datasource:
        name: wenkubao
        url: jdbc:mysql://127.0.0.1:3306/wenkubao?useUnicode=true&characterEncoding=utf8&autoReconnect=true
        username: root
        password: admin

mybatis:
          mapperLocations: classpath:mapper/*.xml
          typeAliasesPackage: com.wenkubao.entity
server:
  port: 80