package com.wenkubao.entity;

import java.util.Date;

public class Userecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.docurl
     *
     * @mbg.generated
     */
    private String docurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.use_ip
     *
     * @mbg.generated
     */
    private String useIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.gmt_date
     *
     * @mbg.generated
     */
    private Date gmtDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.id
     *
     * @return the value of userecord.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.id
     *
     * @param id the value for userecord.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.username
     *
     * @return the value of userecord.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.username
     *
     * @param username the value for userecord.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.docurl
     *
     * @return the value of userecord.docurl
     *
     * @mbg.generated
     */
    public String getDocurl() {
        return docurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.docurl
     *
     * @param docurl the value for userecord.docurl
     *
     * @mbg.generated
     */
    public void setDocurl(String docurl) {
        this.docurl = docurl == null ? null : docurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.use_ip
     *
     * @return the value of userecord.use_ip
     *
     * @mbg.generated
     */
    public String getUseIp() {
        return useIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.use_ip
     *
     * @param useIp the value for userecord.use_ip
     *
     * @mbg.generated
     */
    public void setUseIp(String useIp) {
        this.useIp = useIp == null ? null : useIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.gmt_date
     *
     * @return the value of userecord.gmt_date
     *
     * @mbg.generated
     */
    public Date getGmtDate() {
        return gmtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.gmt_date
     *
     * @param gmtDate the value for userecord.gmt_date
     *
     * @mbg.generated
     */
    public void setGmtDate(Date gmtDate) {
        this.gmtDate = gmtDate;
    }
}