package com.wenkubao.dao;

import com.news.crawler.model.Userecord;
import com.news.crawler.model.UserecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    long countByExample(UserecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int deleteByExample(UserecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int insert(Userecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int insertSelective(Userecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    List<Userecord> selectByExampleWithRowbounds(UserecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    List<Userecord> selectByExample(UserecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    Userecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Userecord record, @Param("example") UserecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Userecord record, @Param("example") UserecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userecord record);
}